### ISSUE TITLE
Make explicit Demo-CA-Lab sections

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby-enumerable-builtins#15]
To be consistent and clear for new instructors (and developers).

**Comment by raq929** [comment]
For the beginning of the repo. I see they're there at the end.

**Comment by jrhorn424** [comment]
Every thing is expository before they're explicit?

**Comment by jrhorn424** [comment]
Can you explain which section I did as a code-along or demo that wasn't?

**Comment by jrhorn424** [comment]
I'm not sure what to do with this. I think every section in the beginning is *supposed* to be expository.
