### ISSUE TITLE
Solution branch is effy

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ruby-enumerable-builtins#6]
It has a different readme, and the code_along.rb is empty.

**Comment by payne-chris-r** [comment]
Yeah, definitely just freaked out ‘cause I switched to the solution branch on github and then started reading the README, and going through the card.rb code-along/lab. I was like, this isn't in the scope of the lesson at all...

**Comment by gaand** [comment]
All the `ruby-enumerable-*` talks are derived from `ruby-enumerable` which ran 9 points or ore and had to be decomposed.

**Comment by BenGitsCode** [comment]
Closed above.
